"""https://leetcode.com/problems/find-the-difference"""


def find_the_diff(s, t):
    """
    Time complexity: O(n)
    Space complexity: O(1)

    Args:
        s(str): Given string s.
        t(str): Given string t. String t is generated by random shuffling
            string s and then add one more letter at a random position.

    Returns:
        The letter that was added to t.

    """
    for c in s:
        t = t.replace(c, "", 1)

    return t
